CREATE TABLE program (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR
);

CREATE TABLE student (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR,
program_id INT REFERENCES program(id) ON DELETE CASCADE
);